# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
  displayName: 'Build Compiler Tooling'
  inputs:
    repository: 'logproxy-builder'
    command: build
    Dockerfile: Dockerfile.build
    tags: latest
- task: Docker@1
  displayName: 'Run the Compiler Build'
  inputs:
    command: 'Run an image'
    arguments: '--rm'
    imageName: 'logproxy-builder'
    containerName: build
    volumes: '$(System.DefaultWorkingDirectory):/src'
    runInBackground: false
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    mergeTestResults: true
    testRunTitle: 'logproxy-unit-tests'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build'